"""AUTO-GENERATED from tests/hacs/__snapshots__/sber_full_spec.json.

DO NOT EDIT BY HAND.  Regenerate with:

    python tools/codegen.py

Source: https://developers.sber.ru/docs/ru/smarthome/c2c
Spec generated at: 2026-04-12T21:05:04.890060+00:00
"""

from __future__ import annotations

FEATURE_TYPES: dict[str, str] = {
    "air_pressure": "INTEGER",
    "alarm_mute": "BOOL",
    "battery_low_power": "BOOL",
    "battery_percentage": "INTEGER",
    "button_10_event": "ENUM",
    "button_1_event": "ENUM",
    "button_2_event": "ENUM",
    "button_3_event": "ENUM",
    "button_4_event": "ENUM",
    "button_5_event": "ENUM",
    "button_6_event": "ENUM",
    "button_7_event": "ENUM",
    "button_8_event": "ENUM",
    "button_9_event": "ENUM",
    "button_bottom_left_event": "ENUM",
    "button_bottom_right_event": "ENUM",
    "button_event": "ENUM",
    "button_left_event": "ENUM",
    "button_right_event": "ENUM",
    "button_top_left_event": "ENUM",
    "button_top_right_event": "ENUM",
    "channel": "ENUM",
    "channel_int": "INTEGER",
    "child_lock": "BOOL",
    "current": "INTEGER",
    "custom_key": "ENUM",
    "direction": "ENUM",
    "doorcontact_state": "BOOL",
    "gas_leak_state": "BOOL",
    "humidity": "INTEGER",
    "hvac_air_flow_direction": "ENUM",
    "hvac_air_flow_power": "ENUM",
    "hvac_aromatization": "BOOL",
    "hvac_decontaminate": "BOOL",
    "hvac_direction_set": "ENUM",
    "hvac_heating_rate": "ENUM",
    "hvac_humidity_set": "INTEGER",
    "hvac_ionization": "BOOL",
    "hvac_night_mode": "BOOL",
    "hvac_replace_filter": "BOOL",
    "hvac_replace_ionizator": "BOOL",
    "hvac_temp_set": "INTEGER",
    "hvac_thermostat_mode": "ENUM",
    "hvac_water_level": "FLOAT",
    "hvac_water_low_level": "BOOL",
    "hvac_water_percentage": "INTEGER",
    "hvac_work_mode": "ENUM",
    "incoming_call": "BOOL",
    "kitchen_water_level": "FLOAT",
    "kitchen_water_low_level": "BOOL",
    "kitchen_water_temperature": "INTEGER",
    "kitchen_water_temperature_set": "INTEGER",
    "light_brightness": "INTEGER",
    "light_colour": "COLOUR",
    "light_colour_temp": "INTEGER",
    "light_mode": "ENUM",
    "light_transmission_percentage": "INTEGER",
    "mute": "BOOL",
    "number": "INTEGER",
    "on_off": "BOOL",
    "online": "BOOL",
    "open_left_percentage": "INTEGER",
    "open_left_set": "ENUM",
    "open_left_state": "ENUM",
    "open_percentage": "INTEGER",
    "open_rate": "ENUM",
    "open_right_percentage": "INTEGER",
    "open_right_set": "ENUM",
    "open_right_state": "ENUM",
    "open_set": "ENUM",
    "open_state": "ENUM",
    "pir": "ENUM",
    "power": "INTEGER",
    "reject_call": "ENUM",
    "sensor_sensitive": "ENUM",
    "signal_strength": "ENUM",
    "smoke_state": "BOOL",
    "source": "ENUM",
    "tamper_alarm": "BOOL",
    "temp_unit_view": "ENUM",
    "temperature": "INTEGER",
    "unlock": "ENUM",
    "vacuum_cleaner_cleaning_type": "ENUM",
    "vacuum_cleaner_command": "ENUM",
    "vacuum_cleaner_program": "ENUM",
    "vacuum_cleaner_status": "ENUM",
    "voltage": "INTEGER",
    "volume": "ENUM",
    "volume_int": "INTEGER",
    "water_leak_state": "BOOL",
}
"""Feature name → Sber value type. Source: developers.sber.ru/docs/ru/smarthome/c2c/functions."""
